enum ActionTypes {
    ADD_ACCOUNT="ADD_ACCOUNT",
    GET_Customer_BY_ID="GET_BY_ID",
    UPDATE_ACCOUNT_STATE="UPDATE_ACCOUNT_STATE",
    FILL_CLASS_CODE_DDL="GET_CLASS_CODE_BY",
    GET_SEARCH_RESULT="GET_SEARCH_RESULT",
    GET_All_CUSTOMERS = "GET_All_CUSTOMER",
    GET_INDEX = "GET_INDEX",
    APPLY_CHANGE = "APPLY_CHANGE",
    FILL_CURRENCY = "FILL_CURRENCY",
    GET_EXCHANGE_RATES = "GET_EXCHANGE_RATES"
}

export default ActionTypes;